### PR TITLE
fuck off red

### PR DESCRIPTION
**Pull request by PJB3005**
this wouldn't have happened if you didn't make fun of my opinion on reddit

### CODE REVIEW

**Comment by PJB3005** [comment]
also i'm not a 100% on this but i think legally you should accept this

**Comment by narcequity** [comment]
was contacted personally about this, he's removing his dead space stuff. merging since he's only removing his own stuff

**Comment by Wizbing** [comment]
I don't know what I'm reading

Please contain the autism

OCEAN MAN 🌊 😍 Take me by the hand ✋ lead me to the land that you understand 🙌 🌊 OCEAN MAN 🌊 😍 The voyage 🚲 to the corner of the 🌎 globe is a real trip 👌 🌊 OCEAN MAN 🌊 😍 The crust of a tan man 👳 imbibed by the sand 👍 Soaking up the 💦 thirst of the land 💯

**Comment by Wizbing** [comment]
OCEAN MAN 🌊 😍 Take me by the hand ✋ lead me to the land that you understand 🙌 🌊 OCEAN MAN 🌊 😍 The voyage 🚲 to the corner of the 🌎 globe is a real trip 👌 🌊 OCEAN MAN 🌊 😍 The crust of a tan man 👳 imbibed by the sand 👍 Soaking up the 💦 thirst of the land 💯

**Pull request merged**
